import json
import os
from typing import List, Optional
from app.schemas.decision import (
    StructuredDecision,
    CriticalThinkingLayerResult,
    FalsifiabilityAuditItem,
    BaseRateComparisonItem
)

class CriticalThinkingEngine:
    """
    Critical Thinking Engine:
    - Falsifiability audit of stated assumptions
    - Base-rate reality check against empirical tables
    - Steelmanning generation
    """

    @classmethod
    def get_base_rates(cls) -> List[dict]:
        kb_path = os.path.join(os.path.dirname(__file__), "..", "knowledge", "base_rates.json")
        with open(kb_path, "r", encoding="utf-8") as f:
            return json.load(f)

    @classmethod
    def evaluate(cls, decision: StructuredDecision, steelmanned_text: Optional[str] = None) -> CriticalThinkingLayerResult:
        base_rates = cls.get_base_rates()

        # 1. Falsifiability Audit
        audit_items: List[FalsifiabilityAuditItem] = []
        for assump in decision.assumptions:
            text_lower = assump.text.lower()
            if assump.testable or any(w in text_lower for w in ["job", "market", "re-employment", "hiring", "compensation", "runway"]):
                grade = "High"
                test_method = "Can be verified within 7-14 days via 2-3 targeted market tests or recruiter informational conversations."
            elif any(w in text_lower for w in ["stagnat", "skills", "learn", "growth"]):
                grade = "Medium"
                test_method = "Testable by attempting a concrete 2-week internal AI build or open-source milestone in your current environment."
            else:
                grade = "Low"
                test_method = "Subjective value attribution; requires testing personal emotional tolerance rather than an empirical dataset."

            audit_items.append(
                FalsifiabilityAuditItem(
                    assumption=assump.text,
                    falsifiability_grade=grade,
                    test_method=test_method
                )
            )

        if not audit_items:
            audit_items.append(
                FalsifiabilityAuditItem(
                    assumption="Finding another equivalent high-paying role in 12-18 months will be difficult.",
                    falsifiability_grade="High",
                    test_method="Discreetly test market demand with 3 peer recruiters to establish current response velocity."
                )
            )

        # 2. Base-Rate Check
        all_text = (
            decision.decision_statement + " " +
            " ".join(a.description for a in decision.alternatives) + " " +
            " ".join(s.name for s in decision.states_of_world)
        ).lower()

        matched_br = None
        for br in base_rates:
            if any(k in all_text for k in br.get("keywords", [])):
                matched_br = br
                break
        if not matched_br and base_rates:
            matched_br = base_rates[0]

        base_rate_item = None
        if matched_br:
            user_p = 0.30
            for s in decision.states_of_world:
                if "win" in s.name.lower() or "succeed" in s.name.lower() or "series a" in s.name.lower():
                    user_p = s.prior_probability
                    break

            emp_rate = matched_br["empirical_base_rate_percentage"]
            divergence_msg = (
                f"Your estimated success probability ({round(user_p * 100, 1)}%) compares against the "
                f"historical industry base rate of {emp_rate}%. "
                f"{'Moderately optimistic relative to reference class.' if user_p * 100 > emp_rate else 'Well aligned with reference class.'}"
            )

            base_rate_item = BaseRateComparisonItem(
                reference_class=matched_br["reference_class"],
                domain=matched_br["domain"],
                source=matched_br["source"],
                empirical_base_rate=emp_rate,
                user_assumption=f"{round(user_p * 100, 1)}% success probability",
                divergence_flag=divergence_msg
            )

        # 3. Steelmanning counterargument (fallback if none generated by LLM)
        if not steelmanned_text:
            steelmanned_text = (
                "The optimal strategy might not be a binary choice between current stagnation and high-risk early startup. "
                "By framing this as 'Stay at current job' vs 'Pre-seed seed startup', you might be overlooking a third alternative: "
                "targeting a well-funded Series B/C scale-up where you get direct frontier AI product ownership with 3+ years of runway."
            )

        return CriticalThinkingLayerResult(
            falsifiability_audit=audit_items,
            base_rate_check=base_rate_item,
            steelmanned_counterargument=steelmanned_text
        )
